// <auto-generated />
#nullable enable

using System;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using RuleSync.Sdk.Models;
#if NETSTANDARD2_1
using RuleSync.Sdk.Polyfills;
#endif

namespace RuleSync.Sdk;

/// <summary>
/// Client for interacting with rulesync from .NET applications.
/// Spawns Node.js process to execute rulesync commands.
/// </summary>
public sealed class RulesyncClient : IDisposable
{
    private readonly string _nodeExecutablePath;
    private readonly string? _rulesyncPath;
    private readonly TimeSpan _timeout;
    private bool _disposed;

    /// <summary>
    /// Creates a new RulesyncClient instance.
    /// </summary>
    /// <param name="nodeExecutablePath">Optional path to Node.js executable. If null, uses "node" from PATH.</param>
    /// <param name="rulesyncPath">Optional path to rulesync package. If null, uses npx rulesync.</param>
    /// <param name="timeout">Optional timeout for operations. Default is 60 seconds.</param>
    public RulesyncClient(
        string? nodeExecutablePath = null,
        string? rulesyncPath = null,
        TimeSpan? timeout = null)
    {
        _nodeExecutablePath = nodeExecutablePath ?? "node";
        _rulesyncPath = rulesyncPath;
        _timeout = timeout ?? TimeSpan.FromSeconds(60);
    }

    /// <summary>
    /// Generates AI tool configurations based on the provided options.
    /// </summary>
    /// <param name="options">Generation options</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>Result of the generation operation</returns>
    public async ValueTask<Result<GenerateResult>> GenerateAsync(
        GenerateOptions? options = null,
        CancellationToken cancellationToken = default)
    {
        ThrowIfDisposed();

        try
        {
            var opts = options ?? new GenerateOptions();
            var args = BuildGenerateArgs(opts);
            var result = await ExecuteRulesyncAsync(args, cancellationToken).ConfigureAwait(false);

            if (result.ExitCode != 0)
            {
                return Result<GenerateResult>.Failure(
                    "GENERATE_FAILED",
                    $"Rulesync generate failed with exit code {result.ExitCode}: {result.Stderr}");
            }

            var generateResult = JsonSerializer.Deserialize<GenerateResult>(result.Stdout);
            if (generateResult == null)
            {
                return Result<GenerateResult>.Failure(
                    "DESERIALIZATION_FAILED",
                    "Failed to deserialize generate result.");
            }

            return Result<GenerateResult>.Success(generateResult);
        }
        catch (Exception ex)
        {
            return Result<GenerateResult>.Failure(
                "EXCEPTION",
                $"An error occurred during generate: {ex.Message}");
        }
    }

    /// <summary>
    /// Imports configuration from an existing AI tool.
    /// </summary>
    /// <param name="options">Import options (target is required)</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>Result of the import operation</returns>
    public async ValueTask<Result<ImportResult>> ImportAsync(
        ImportOptions options,
        CancellationToken cancellationToken = default)
    {
        ThrowIfDisposed();

        try
        {
            var args = BuildImportArgs(options);
            var result = await ExecuteRulesyncAsync(args, cancellationToken).ConfigureAwait(false);

            if (result.ExitCode != 0)
            {
                return Result<ImportResult>.Failure(
                    "IMPORT_FAILED",
                    $"Rulesync import failed with exit code {result.ExitCode}: {result.Stderr}");
            }

            var importResult = JsonSerializer.Deserialize<ImportResult>(result.Stdout);
            if (importResult == null)
            {
                return Result<ImportResult>.Failure(
                    "DESERIALIZATION_FAILED",
                    "Failed to deserialize import result.");
            }

            return Result<ImportResult>.Success(importResult);
        }
        catch (Exception ex)
        {
            return Result<ImportResult>.Failure(
                "EXCEPTION",
                $"An error occurred during import: {ex.Message}");
        }
    }

    /// <summary>
    /// Disposes the client.
    /// </summary>
    public void Dispose()
    {
        _disposed = true;
    }

    private void ThrowIfDisposed()
    {
        if (_disposed)
        {
            throw new ObjectDisposedException(nameof(RulesyncClient));
        }
    }

    private string[] BuildGenerateArgs(GenerateOptions options)
    {
        var args = new StringBuilder();
        args.Append("generate");

        if (options.Targets?.Count > 0)
        {
            args.Append(" --targets ");
            args.Append(string.Join(",", options.Targets));
        }

        if (options.Features?.Count > 0)
        {
            args.Append(" --features ");
            args.Append(string.Join(",", options.Features.Select(f => f.ToString().ToLowerInvariant())));
        }

        if (options.Verbose == true) args.Append(" --verbose");
        if (options.Silent == false) args.Append(" --no-silent");
        if (options.Delete == true) args.Append(" --delete");
        if (options.Global == true) args.Append(" --global");
        if (options.SimulateCommands == true) args.Append(" --simulate-commands");
        if (options.SimulateSubagents == true) args.Append(" --simulate-subagents");
        if (options.SimulateSkills == true) args.Append(" --simulate-skills");
        if (options.DryRun == true) args.Append(" --dry-run");
        if (options.Check == true) args.Append(" --check");

        if (!string.IsNullOrEmpty(options.ConfigPath))
        {
            args.Append(" --config ");
            args.Append(options.ConfigPath);
        }

        // Add JSON output flag
        args.Append(" --json");

        return args.ToString().Split(' ', StringSplitOptions.RemoveEmptyEntries);
    }

    private string[] BuildImportArgs(ImportOptions options)
    {
        var args = new StringBuilder();
        args.Append("import");
        args.Append(" --target ");
        args.Append(options.Target.ToString().ToLowerInvariant());

        if (options.Features?.Count > 0)
        {
            args.Append(" --features ");
            args.Append(string.Join(",", options.Features.Select(f => f.ToString().ToLowerInvariant())));
        }

        if (options.Verbose == true) args.Append(" --verbose");
        if (options.Silent == false) args.Append(" --no-silent");
        if (options.Global == true) args.Append(" --global");

        if (!string.IsNullOrEmpty(options.ConfigPath))
        {
            args.Append(" --config ");
            args.Append(options.ConfigPath);
        }

        // Add JSON output flag
        args.Append(" --json");

        return args.ToString().Split(' ', StringSplitOptions.RemoveEmptyEntries);
    }

    private async Task<ProcessResult> ExecuteRulesyncAsync(
        string[] args,
        CancellationToken cancellationToken)
    {
        var startInfo = new ProcessStartInfo
        {
            FileName = _nodeExecutablePath,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true
        };

        if (_rulesyncPath != null)
        {
            // Direct path to rulesync module
            startInfo.ArgumentList.Add(Path.Combine(_rulesyncPath, "dist", "cli.js"));
        }
        else
        {
            // Use npx
            startInfo.FileName = "npx";
            startInfo.ArgumentList.Add("rulesync");
        }

        foreach (var arg in args)
        {
            startInfo.ArgumentList.Add(arg);
        }

        using var process = new Process { StartInfo = startInfo };
        var stdoutBuilder = new StringBuilder();
        var stderrBuilder = new StringBuilder();

        process.OutputDataReceived += (sender, e) =>
        {
            if (e.Data != null) stdoutBuilder.AppendLine(e.Data);
        };

        process.ErrorDataReceived += (sender, e) =>
        {
            if (e.Data != null) stderrBuilder.AppendLine(e.Data);
        };

        process.Start();
        process.BeginOutputReadLine();
        process.BeginErrorReadLine();

        using var cts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
        cts.CancelAfter(_timeout);

        try
        {
            await process.WaitForExitAsync(cts.Token).ConfigureAwait(false);
        }
        catch (OperationCanceledException)
        {
            process.Kill();
            throw new TimeoutException($"Rulesync operation timed out after {_timeout.TotalSeconds} seconds.");
        }

        return new ProcessResult(
            process.ExitCode,
            stdoutBuilder.ToString(),
            stderrBuilder.ToString());
    }

    private readonly record struct ProcessResult(int ExitCode, string Stdout, string Stderr);
}
