#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using RuleSync.Sdk.Models;

namespace RuleSync.Sdk.Serialization;

/// <summary>
/// JSON serialization helpers for Rulesync models.
/// </summary>
/// <remarks>
/// Note: Full Native AOT compatibility requires compile-time type visibility.
/// Since GenerateResult and ImportResult are dynamically generated by the source generator,
/// they cannot be annotated with [JsonSerializable] attributes.
/// This implementation uses reflection-based deserialization with proper trimming annotations.
/// </remarks>
internal static class RulesyncJsonContext
{
    // Static options with all converters configured
    private static readonly JsonSerializerOptions s_options = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        NumberHandling = JsonNumberHandling.Strict,
        MaxDepth = 64,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.CamelCase) }
    };

    /// <summary>
    /// Deserializes a GenerateResult from JSON.
    /// </summary>
#if NET6_0_OR_GREATER
    [System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("JSON serialization requires unreferenced code")]
#endif
#if NET7_0_OR_GREATER
    [System.Diagnostics.CodeAnalysis.RequiresDynamicCode("JSON serialization requires dynamic code")]
#endif
    internal static GenerateResult? DeserializeGenerateResult(string json)
    {
        return JsonSerializer.Deserialize<GenerateResult>(json, s_options);
    }

    /// <summary>
    /// Deserializes an ImportResult from JSON.
    /// </summary>
#if NET6_0_OR_GREATER
    [System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("JSON serialization requires unreferenced code")]
#endif
#if NET7_0_OR_GREATER
    [System.Diagnostics.CodeAnalysis.RequiresDynamicCode("JSON serialization requires dynamic code")]
#endif
    internal static ImportResult? DeserializeImportResult(string json)
    {
        return JsonSerializer.Deserialize<ImportResult>(json, s_options);
    }
}
