// <auto-generated />
#nullable enable

#if NETSTANDARD2_1
using System;
using System.Diagnostics;
using System.Threading;
using System.Threading.Tasks;

namespace RuleSync.Sdk.Polyfills;

/// <summary>Polyfill for WaitForExitAsync on .NET Standard 2.1.</summary>
internal static class ProcessExtensions
{
    public static Task WaitForExitAsync(this Process process, CancellationToken cancellationToken = default)
    {
        if (process.HasExited)
            return Task.CompletedTask;

        var tcs = new TaskCompletionSource<object?>();

        void OnExited(object? sender, EventArgs e)
        {
            process.Exited -= OnExited;
            tcs.TrySetResult(null);
        }

        process.EnableRaisingEvents = true;
        process.Exited += OnExited;

        if (process.HasExited)
        {
            process.Exited -= OnExited;
            tcs.TrySetResult(null);
        }

        if (cancellationToken.CanBeCanceled)
        {
            var registration = cancellationToken.Register(() =>
            {
                process.Exited -= OnExited;
                tcs.TrySetCanceled(cancellationToken);
            });

            return tcs.Task.ContinueWith(
                _ => registration.Dispose(),
                TaskContinuationOptions.ExecuteSynchronously);
        }

        return tcs.Task;
    }
}
#endif
