import { join } from "node:path";

import { ANTIGRAVITY_DIR, ANTIGRAVITY_GEMINI_DIR } from "./antigravity-paths.js";

export {
  ANTIGRAVITY_GEMINI_DIR,
  ANTIGRAVITY_GLOBAL_CONFIG_DIR_PATH,
  ANTIGRAVITY_GLOBAL_CONFIG_SUBDIR,
  ANTIGRAVITY_HOOKS_FILE_NAME,
  ANTIGRAVITY_IGNORE_FILE_NAME,
  ANTIGRAVITY_MCP_FILE_NAME,
  ANTIGRAVITY_RULES_DIR_PATH,
  ANTIGRAVITY_SKILLS_DIR_PATH,
} from "./antigravity-paths.js";

export const ANTIGRAVITY_AGENTS_DIR = ANTIGRAVITY_DIR;

export const ANTIGRAVITY_RULE_FILE_NAME = "GEMINI.md";

export const ANTIGRAVITY_CLI_GLOBAL_SUBDIR = "antigravity-cli";
export const ANTIGRAVITY_CLI_PERMISSIONS_DIR_PATH = join(
  ANTIGRAVITY_GEMINI_DIR,
  ANTIGRAVITY_CLI_GLOBAL_SUBDIR,
);
export const ANTIGRAVITY_CLI_PERMISSIONS_FILE_NAME = "settings.json";
