import { isAbsolute, join, normalize } from "node:path";

import { z } from "zod/mini";

import { SKILL_FILE_NAME } from "../../constants/general.js";
import {
  OPENCODE_GLOBAL_SKILL_DIR_PATH,
  OPENCODE_GLOBAL_SKILLS_DIR_PATH,
  OPENCODE_SKILL_DIR_PATH,
  OPENCODE_SKILLS_DIR_PATH,
} from "../../constants/opencode-paths.js";
import { RULESYNC_SKILLS_RELATIVE_DIR_PATH } from "../../constants/rulesync-paths.js";
import { ValidationResult } from "../../types/ai-dir.js";
import { formatError } from "../../utils/error.js";
import { resolvedPathEscapesRoot } from "../../utils/file.js";
import { asOpencodeEntries, getOpencodeConfigDir, readOpencodeConfig } from "../opencode-config.js";
import { RulesyncSkill, RulesyncSkillFrontmatterInput, SkillFile } from "./rulesync-skill.js";
import { resolveCompatibility, resolveLicense, resolveMetadata } from "./skills-utils.js";
import {
  ToolSkill,
  ToolSkillForDeletionParams,
  ToolSkillFromDirParams,
  ToolSkillFromRulesyncSkillParams,
  ToolSkillSettablePaths,
} from "./tool-skill.js";

export const OpenCodeSkillFrontmatterSchema = z.looseObject({
  name: z.string(),
  description: z.string(),
  // OpenCode's docs mention `name`, `description`, `license`, `compatibility`,
  // and `metadata` (https://opencode.ai/docs/skills/), but the actual
  // `Frontmatter` schema it parses SKILL.md with (`packages/core/src/skill.ts`
  // in sst/opencode) does not define `license`, `compatibility`, or
  // `metadata` at all, so it never validates or rejects them. Left untyped so
  // rulesync never aborts on a value the underlying tool itself tolerates.
  license: z.optional(z.unknown()),
  compatibility: z.optional(z.unknown()),
  metadata: z.optional(z.unknown()),
  // `allowed-tools` is NOT recognized by OpenCode (it is an Anthropic-spec
  // field that OpenCode silently ignores). It is kept as an optional
  // passthrough purely for lossless round-trip with the rulesync frontmatter.
  "allowed-tools": z.optional(z.array(z.string())),
});

export type OpenCodeSkillFrontmatter = z.infer<typeof OpenCodeSkillFrontmatterSchema>;

export type OpenCodeSkillParams = {
  outputRoot?: string;
  relativeDirPath?: string;
  dirName: string;
  frontmatter: OpenCodeSkillFrontmatter;
  body: string;
  otherFiles?: SkillFile[];
  validate?: boolean;
  global?: boolean;
};

export class OpenCodeSkill extends ToolSkill {
  constructor({
    outputRoot = process.cwd(),
    relativeDirPath = OPENCODE_SKILLS_DIR_PATH,
    dirName,
    frontmatter,
    body,
    otherFiles = [],
    validate = true,
    global = false,
  }: OpenCodeSkillParams) {
    super({
      outputRoot,
      relativeDirPath,
      dirName,
      mainFile: {
        name: SKILL_FILE_NAME,
        body,
        frontmatter: { ...frontmatter },
      },
      otherFiles,
      global,
    });

    if (validate) {
      const result = this.validate();
      if (!result.success) {
        throw result.error;
      }
    }
  }

  static getSettablePaths({ global = false }: { global?: boolean } = {}): ToolSkillSettablePaths {
    // OpenCode's canonical directory is the plural `skills/`. The singular
    // `skill/` is kept as an alternative search root so existing projects that
    // were generated by older rulesync versions (or hand-authored with the
    // legacy singular name, which OpenCode still loads for backwards
    // compatibility) continue to import correctly.
    return {
      relativeDirPath: global ? OPENCODE_GLOBAL_SKILLS_DIR_PATH : OPENCODE_SKILLS_DIR_PATH,
      alternativeSkillRoots: [global ? OPENCODE_GLOBAL_SKILL_DIR_PATH : OPENCODE_SKILL_DIR_PATH],
    };
  }

  /**
   * Extra skill roots the project configured in `opencode.json` /
   * `opencode.jsonc` via `skills.paths` ("Additional paths to skill folders").
   * Without these, skills a project keeps outside `.opencode/skills/` are
   * invisible to `rulesync import` even though OpenCode loads them.
   *
   * Import-only: rulesync keeps writing to its own managed root, so a
   * configured path is read but never generated into. `skills.urls` is a
   * remote-fetch surface and is out of scope for a file-based generator.
   *
   * Absolute paths and paths escaping the config directory are dropped — an
   * import root is joined onto that directory, and reaching outside it is not
   * something a project config should be able to ask for. A path is judged by
   * where it resolves, not by how it is spelled: a relative name that is a
   * symbolic link pointing out of the directory is an escape all the same and
   * is dropped too. A path that does not exist has nothing to resolve and is
   * compared as spelled against the resolved config directory, so it survives
   * only when that directory resolves to its own spelling and is dropped when
   * the directory is itself reached through a link. Either way it yields no
   * skills — the scan finds no directory under it.
   *
   * @see https://opencode.ai/config.json
   */
  static async getConfiguredImportRoots({
    outputRoot,
    global = false,
  }: {
    outputRoot: string;
    global?: boolean;
  }): Promise<Array<{ outputRoot: string; relativeDirPath: string }>> {
    const config = await readOpencodeConfig({ outputRoot, global });
    const skills = asOpencodeEntries(config.skills);
    if (skills === null || !Array.isArray(skills.paths)) {
      return [];
    }
    // Resolved against the directory the config itself was read from, which is
    // what OpenCode does — in global mode that is `~/.config/opencode/`, not
    // the home directory.
    const configDir = getOpencodeConfigDir({ outputRoot, global });
    const lexicallyContained = skills.paths.filter(
      (candidate): candidate is string =>
        typeof candidate === "string" &&
        candidate !== "" &&
        !isAbsolute(candidate) &&
        !normalize(candidate).startsWith(".."),
    );
    // The lexical test above reads a path as it is spelled, so a name inside
    // the config directory that is a link out of it passes and would be read.
    // Resolving both sides catches the link, the same way a nested Claude Code
    // skills root is judged. Dropped silently, like the lexical drops above.
    const escapes = await Promise.all(
      lexicallyContained.map((candidate) =>
        resolvedPathEscapesRoot({ rootPath: configDir, targetPath: join(configDir, candidate) }),
      ),
    );
    return lexicallyContained
      .filter((_, index) => !escapes[index])
      .map((relativeDirPath) => ({ outputRoot: configDir, relativeDirPath }));
  }

  getFrontmatter(): OpenCodeSkillFrontmatter {
    const result = OpenCodeSkillFrontmatterSchema.parse(this.requireMainFileFrontmatter());
    return result;
  }

  getBody(): string {
    return this.mainFile?.body ?? "";
  }

  validate(): ValidationResult {
    if (this.mainFile === undefined) {
      return {
        success: false,
        error: new Error(`${this.getDirPath()}: ${SKILL_FILE_NAME} file does not exist`),
      };
    }
    const result = OpenCodeSkillFrontmatterSchema.safeParse(this.mainFile.frontmatter);
    if (!result.success) {
      return {
        success: false,
        error: new Error(
          `Invalid frontmatter in ${this.getDirPath()}: ${formatError(result.error)}`,
        ),
      };
    }

    return { success: true, error: null };
  }

  toRulesyncSkill(): RulesyncSkill {
    const frontmatter = this.getFrontmatter();
    const opencodeBlock = {
      ...(frontmatter["allowed-tools"] !== undefined && {
        "allowed-tools": frontmatter["allowed-tools"],
      }),
      ...(frontmatter.license !== undefined && { license: frontmatter.license }),
      ...(frontmatter.compatibility !== undefined && {
        compatibility: frontmatter.compatibility,
      }),
      ...(frontmatter.metadata !== undefined && { metadata: frontmatter.metadata }),
    };
    const rulesyncFrontmatter: RulesyncSkillFrontmatterInput = {
      name: frontmatter.name,
      description: frontmatter.description,
      targets: ["*"],
      ...(Object.keys(opencodeBlock).length > 0 && { opencode: opencodeBlock }),
    };

    return new RulesyncSkill({
      outputRoot: this.outputRoot,
      relativeDirPath: RULESYNC_SKILLS_RELATIVE_DIR_PATH,
      dirName: this.getDirName(),
      frontmatter: rulesyncFrontmatter,
      body: this.getBody(),
      otherFiles: this.getOtherFiles(),
      validate: true,
      global: this.global,
    });
  }

  static fromRulesyncSkill({
    outputRoot = process.cwd(),
    rulesyncSkill,
    validate = true,
    global = false,
  }: ToolSkillFromRulesyncSkillParams): OpenCodeSkill {
    const rulesyncFrontmatter = rulesyncSkill.getFrontmatter();
    const opencodeSection = rulesyncFrontmatter.opencode;

    // Source precedence: the `opencode` section value takes priority, falling
    // back to the root-level rulesync frontmatter value when present.
    const license = resolveLicense({
      rootFrontmatter: rulesyncFrontmatter,
      section: opencodeSection,
    });
    const compatibility = resolveCompatibility({
      rootFrontmatter: rulesyncFrontmatter,
      section: opencodeSection,
    });
    const metadata = resolveMetadata({
      rootFrontmatter: rulesyncFrontmatter,
      section: opencodeSection,
    });

    const opencodeFrontmatter: OpenCodeSkillFrontmatter = {
      name: rulesyncFrontmatter.name,
      description: rulesyncFrontmatter.description,
      ...(license !== undefined && { license }),
      ...(compatibility !== undefined && { compatibility }),
      ...(metadata !== undefined && { metadata }),
      ...(opencodeSection?.["allowed-tools"] !== undefined && {
        "allowed-tools": opencodeSection["allowed-tools"],
      }),
    };

    const settablePaths = OpenCodeSkill.getSettablePaths({ global });

    return new OpenCodeSkill({
      outputRoot,
      relativeDirPath: settablePaths.relativeDirPath,
      dirName: rulesyncSkill.getDirName(),
      frontmatter: opencodeFrontmatter,
      body: rulesyncSkill.getBody(),
      otherFiles: rulesyncSkill.getOtherFiles(),
      validate,
      global,
    });
  }

  static isTargetedByRulesyncSkill(rulesyncSkill: RulesyncSkill): boolean {
    const targets = rulesyncSkill.getFrontmatter().targets;
    return targets.includes("*") || targets.includes("opencode");
  }

  static async fromDir(params: ToolSkillFromDirParams): Promise<OpenCodeSkill> {
    const loaded = await this.loadSkillDirContent({
      ...params,
      getSettablePaths: OpenCodeSkill.getSettablePaths,
    });

    const result = OpenCodeSkillFrontmatterSchema.safeParse(loaded.frontmatter);
    if (!result.success) {
      const skillDirPath = join(loaded.outputRoot, loaded.relativeDirPath, loaded.dirName);
      throw new Error(
        `Invalid frontmatter in ${join(skillDirPath, SKILL_FILE_NAME)}: ${formatError(result.error)}`,
      );
    }

    return new OpenCodeSkill({
      outputRoot: loaded.outputRoot,
      relativeDirPath: loaded.relativeDirPath,
      dirName: loaded.dirName,
      frontmatter: result.data,
      body: loaded.body,
      otherFiles: loaded.otherFiles,
      validate: true,
      global: loaded.global,
    });
  }

  static forDeletion({
    outputRoot = process.cwd(),
    relativeDirPath,
    dirName,
    global = false,
  }: ToolSkillForDeletionParams): OpenCodeSkill {
    return new OpenCodeSkill({
      outputRoot,
      relativeDirPath,
      dirName,
      frontmatter: { name: "", description: "" },
      body: "",
      otherFiles: [],
      validate: false,
      global,
    });
  }
}
