// Per-feature tool-target tuples; `ALL_TOOL_TARGETS` is their union (tool-targets.ts).
// Keep this a leaf module (no imports) so feature processors can import their tuple
// without a cycle through `ToolTarget`.

export const rulesProcessorToolTargetTuple = [
  "agentsmd",
  "aiassistant",
  "amp",
  "antigravity-cli",
  "antigravity-ide",
  "antigravity-plugin",
  "augmentcode",
  "augmentcode-legacy",
  "bob",
  "claudecode",
  "claudecode-legacy",
  "cline",
  "codebuddy",
  "codexcli",
  "copilot",
  "copilotcli",
  "cortexcode",
  "crush",
  "cursor",
  "deepagents",
  "factorydroid",
  "goose",
  "grokcli",
  "hermesagent",
  "junie",
  "kilo",
  "kimi-code",
  "kiro",
  "kiro-cli",
  "kiro-ide",
  "musecode",
  "opencode",
  "pi",
  "qwencode",
  "reasonix",
  "replit",
  "roo",
  "rovodev",
  "tabnine",
  "takt",
  "vibe",
  "warp",
  "devin",
  "zcode",
  "zed",
  "zoocode",
  "pool",
  "dsh",
] as const;

export const ignoreProcessorToolTargetTuple = [
  "aiassistant",
  "antigravity-cli",
  "augmentcode",
  "bob",
  "claudecode",
  "claudecode-legacy",
  "cline",
  "crush",
  "cursor",
  "hermesagent",
  "junie",
  "kilo",
  "kiro",
  "kiro-cli",
  "kiro-ide",
  "qwencode",
  "reasonix",
  "roo",
  "tabnine",
  "devin",
  "vibe",
  "warp",
  "zed",
  "zoocode",
] as const;

export const mcpProcessorToolTargetTuple = [
  "aiassistant",
  "amp",
  "antigravity-cli",
  "antigravity-ide",
  "antigravity-plugin",
  "augmentcode",
  "bob",
  "claudecode",
  "claudecode-plugin",
  "claudecode-legacy",
  "cline",
  "codexcli",
  "copilot",
  "copilotcli",
  "cortexcode",
  "cursor",
  "deepagents",
  "factorydroid",
  "goose",
  "grokcli",
  "hermesagent",
  "kimi-code",
  "kilo",
  "kiro",
  "kiro-cli",
  "kiro-ide",
  "junie",
  "musecode",
  "opencode",
  "qwencode",
  "reasonix",
  "roo",
  "rovodev",
  "tabnine",
  "takt",
  "vibe",
  "warp",
  "devin",
  "zcode",
  "zed",
  "zoocode",
] as const;

export const commandsProcessorToolTargetTuple = [
  "agentsmd",
  "antigravity-cli",
  "antigravity-ide",
  "augmentcode",
  "bob",
  "claudecode",
  "claudecode-plugin",
  "claudecode-legacy",
  "cline",
  "codexcli",
  "copilot",
  "cursor",
  "factorydroid",
  "goose",
  "grokcli",
  "hermesagent",
  "junie",
  "kilo",
  "kiro",
  "kiro-cli",
  "kiro-ide",
  "opencode",
  "pi",
  "qwencode",
  "reasonix",
  "roo",
  "zoocode",
  "rovodev",
  "tabnine",
  "takt",
  "devin",
  "warp",
  "zcode",
] as const;

export const subagentsProcessorToolTargetTuple = [
  "kilo",
  "agentsmd",
  "antigravity-cli",
  "antigravity-ide",
  "antigravity-plugin",
  "augmentcode",
  "claudecode",
  "claudecode-plugin",
  "claudecode-legacy",
  "cline",
  "codexcli",
  "copilot",
  "copilotcli",
  "cortexcode",
  "cursor",
  "deepagents",
  "devin",
  "factorydroid",
  "goose",
  "grokcli",
  "hermesagent",
  "kimi-code",
  "junie",
  "kiro",
  "kiro-cli",
  "kiro-ide",
  "opencode",
  "qwencode",
  "reasonix",
  "roo",
  // Must stay AFTER "roo": both write the workspace-root `.roomodes`, and the
  // zoocode aggregate (which carries `allowedMcpServers`) must be the survivor
  // when both targets are enabled. Guarded by a test in
  // zoocode-subagent.test.ts.
  "zoocode",
  "rovodev",
  "tabnine",
  "takt",
  "vibe",
  "zcode",
] as const;

export const skillsProcessorToolTargetTuple = [
  "agentsmd",
  "agentsskills",
  "aiassistant",
  "amp",
  "antigravity-cli",
  "antigravity-ide",
  "antigravity-plugin",
  "augmentcode",
  "bob",
  "claudecode",
  "claudecode-plugin",
  "claudecode-legacy",
  "cline",
  "codexcli",
  "copilot",
  "copilotcli",
  "cortexcode",
  "crush",
  "cursor",
  "deepagents",
  "factorydroid",
  "goose",
  "grokcli",
  "hermesagent",
  "kimi-code",
  "junie",
  "kilo",
  "kiro",
  "kiro-cli",
  "kiro-ide",
  "musecode",
  "opencode",
  "pi",
  "qwencode",
  "reasonix",
  "replit",
  "roo",
  "rovodev",
  "tabnine",
  "takt",
  "vibe",
  "warp",
  "devin",
  "zcode",
  "zed",
  "zoocode",
  "dsh",
] as const;

export const hooksProcessorToolTargetTuple = [
  "amp",
  "cline",
  "antigravity-cli",
  "antigravity-ide",
  "antigravity-plugin",
  "kilo",
  "cursor",
  "claudecode",
  "claudecode-plugin",
  "codexcli",
  "copilot",
  "copilotcli",
  "cortexcode",
  "opencode",
  "pi",
  "factorydroid",
  "goose",
  "hermesagent",
  "kimi-code",
  "deepagents",
  "kiro",
  "kiro-cli",
  "kiro-ide",
  "devin",
  "augmentcode",
  "bob",
  "junie",
  "vibe",
  "qwencode",
  "reasonix",
  "tabnine",
  "grokcli",
  "zcode",
] as const;

export const permissionsProcessorToolTargetTuple = [
  "amp",
  "antigravity-cli",
  "antigravity-ide",
  "augmentcode",
  "claudecode",
  "cline",
  "codexcli",
  "copilot",
  "copilotcli",
  "cursor",
  "deepagents",
  "devin",
  "factorydroid",
  "goose",
  "grokcli",
  "hermesagent",
  "kimi-code",
  "junie",
  "kilo",
  "kiro",
  "kiro-cli",
  "kiro-ide",
  "opencode",
  "pi",
  "qwencode",
  "reasonix",
  "roo",
  "rovodev",
  "tabnine",
  "takt",
  "vibe",
  "warp",
  "zed",
  "zoocode",
] as const;

export const checksProcessorToolTargetTuple = [
  "amp",
  "augmentcode",
  "cursor",
  "factorydroid",
  "hermesagent",
  "rovodev",
  "takt",
] as const;

export const ALL_TOOL_TARGET_TUPLES = [
  rulesProcessorToolTargetTuple,
  ignoreProcessorToolTargetTuple,
  mcpProcessorToolTargetTuple,
  commandsProcessorToolTargetTuple,
  subagentsProcessorToolTargetTuple,
  skillsProcessorToolTargetTuple,
  hooksProcessorToolTargetTuple,
  permissionsProcessorToolTargetTuple,
  checksProcessorToolTargetTuple,
] as const;
