import { execFile } from "node:child_process";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { promisify } from "node:util";

import { tsImport } from "tsx/esm/api";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import { RULESYNC_RELATIVE_DIR_PATH } from "../../constants/rulesync-paths.js";
import { setupTestDirectory } from "../../test-utils/test-directories.js";
import { ensureDir, readFileContent, writeFileContent } from "../../utils/file.js";
import { AmpHooks } from "./amp-hooks.js";
import { RulesyncHooks } from "./rulesync-hooks.js";

const execFileAsync = promisify(execFile);

function buildRulesyncHooks({
  testDir,
  config,
}: {
  testDir: string;
  config: Record<string, unknown>;
}): RulesyncHooks {
  return new RulesyncHooks({
    outputRoot: testDir,
    relativeDirPath: RULESYNC_RELATIVE_DIR_PATH,
    relativeFilePath: "hooks.json",
    fileContent: JSON.stringify(config),
    validate: false,
  });
}

describe("AmpHooks", () => {
  let testDir: string;
  let cleanup: () => Promise<void>;

  beforeEach(async () => {
    ({ testDir, cleanup } = await setupTestDirectory());
    vi.spyOn(process, "cwd").mockReturnValue(testDir);
  });

  afterEach(async () => {
    await cleanup();
    vi.restoreAllMocks();
  });

  it("should return project and global plugin paths", () => {
    expect(AmpHooks.getSettablePaths()).toEqual({
      relativeDirPath: join(".amp", "plugins"),
      relativeFilePath: "rulesync-hooks.ts",
    });
    expect(AmpHooks.getSettablePaths({ global: true })).toEqual({
      relativeDirPath: join(".config", "amp", "plugins"),
      relativeFilePath: "rulesync-hooks.ts",
    });
  });

  it("should map the faithful Amp lifecycle events and skip unsupported events", () => {
    const ampHooks = AmpHooks.fromRulesyncHooks({
      outputRoot: testDir,
      rulesyncHooks: buildRulesyncHooks({
        testDir,
        config: {
          hooks: {
            sessionStart: [{ command: "session.sh" }],
            preToolUse: [{ command: "pre.sh", matcher: "Write|Edit" }],
            postToolUse: [{ command: "post.sh" }],
            beforeSubmitPrompt: [
              { command: "prompt.sh" },
              { command: "filtered-prompt.sh", matcher: "special" },
            ],
            stop: [{ command: "stop.sh" }],
            subagentStart: [{ command: "subagent.sh" }],
          },
        },
      }),
      validate: false,
    });

    const content = ampHooks.getFileContent();
    expect(content).toContain('amp.on("session.start"');
    expect(content).toContain('amp.on("tool.call"');
    expect(content).toContain('amp.on("tool.result"');
    expect(content).toContain('amp.on("agent.start"');
    expect(content).toContain('amp.on("agent.end"');
    expect(content).toContain('new RegExp("Write|Edit").test(event.tool)');
    expect(content).not.toContain("subagent.sh");
    expect(content).not.toContain("filtered-prompt.sh");
  });

  it("should let the Amp override replace shared hooks", () => {
    const ampHooks = AmpHooks.fromRulesyncHooks({
      outputRoot: testDir,
      rulesyncHooks: buildRulesyncHooks({
        testDir,
        config: {
          hooks: { sessionStart: [{ command: "shared.sh" }] },
          amp: {
            hooks: {
              sessionStart: [{ command: "amp.sh" }],
              stop: [{ command: "amp-stop.sh" }],
            },
          },
        },
      }),
      validate: false,
    });

    expect(ampHooks.getFileContent()).toContain("amp.sh");
    expect(ampHooks.getFileContent()).toContain("amp-stop.sh");
    expect(ampHooks.getFileContent()).not.toContain("shared.sh");
  });

  it("should skip non-command hooks and emit an inert plugin when nothing remains", () => {
    const ampHooks = AmpHooks.fromRulesyncHooks({
      outputRoot: testDir,
      rulesyncHooks: buildRulesyncHooks({
        testDir,
        config: {
          hooks: { sessionStart: [{ type: "prompt", prompt: "Remember this" }] },
        },
      }),
      validate: false,
    });

    expect(ampHooks.getFileContent()).toBe(
      ["// Generated by rulesync. Do not edit manually.", "export default function () {}", ""].join(
        "\n",
      ),
    );
  });

  it("should embed commands as raw Bun Shell values and validate matcher regular expressions", () => {
    const command = 'echo "C:\\temp" $(date) ${HOME}';
    const ampHooks = AmpHooks.fromRulesyncHooks({
      outputRoot: testDir,
      rulesyncHooks: buildRulesyncHooks({
        testDir,
        config: { hooks: { sessionStart: [{ command }] } },
      }),
      validate: false,
    });
    expect(ampHooks.getFileContent()).toContain(
      'ctx.$`${{ raw: "echo \\"C:\\\\temp\\" $(date) ${HOME}" }}`',
    );

    expect(() =>
      AmpHooks.fromRulesyncHooks({
        outputRoot: testDir,
        rulesyncHooks: buildRulesyncHooks({
          testDir,
          config: { hooks: { preToolUse: [{ command: "guard.sh", matcher: "[invalid" }] } },
        }),
        validate: false,
      }),
    ).toThrow("Invalid regex pattern in hook matcher");
  });

  it("should generate a loadable plugin and enforce pre-tool command failures", async () => {
    const ampHooks = AmpHooks.fromRulesyncHooks({
      outputRoot: testDir,
      rulesyncHooks: buildRulesyncHooks({
        testDir,
        config: {
          hooks: {
            preToolUse: [{ command: "guard.sh", matcher: "Write" }],
            stop: [{ command: "done.sh" }],
          },
        },
      }),
      validate: false,
    });
    const pluginsDir = join(testDir, ".amp", "plugins");
    await ensureDir(pluginsDir);
    const filePath = join(pluginsDir, "rulesync-hooks.ts");
    await writeFileContent(filePath, ampHooks.getFileContent());

    const module = await tsImport(pathToFileURL(filePath).href, import.meta.url);
    const on = vi.fn();
    module.default({ on });
    const handlers = Object.fromEntries(on.mock.calls.map(([event, handler]) => [event, handler]));
    const shell = vi
      .fn()
      .mockResolvedValueOnce({ exitCode: 0, stdout: "", stderr: "" })
      .mockResolvedValueOnce({ exitCode: 7, stdout: "", stderr: "blocked by policy\n" });

    await expect(handlers["tool.call"]({ tool: "Read" }, { $: shell })).resolves.toEqual({
      action: "allow",
    });
    expect(shell).not.toHaveBeenCalled();

    await expect(handlers["tool.call"]({ tool: "Write" }, { $: shell })).resolves.toEqual({
      action: "allow",
    });
    await expect(handlers["tool.call"]({ tool: "Write" }, { $: shell })).resolves.toEqual({
      action: "reject-and-continue",
      message: "blocked by policy",
    });

    shell.mockRejectedValueOnce(new Error("hook execution failed"));
    await expect(handlers["tool.call"]({ tool: "Write" }, { $: shell })).resolves.toEqual({
      action: "reject-and-continue",
      message: "hook execution failed",
    });
  });

  it("should preserve shell quoting and expansion when executed by Bun Shell", async () => {
    const outputPath = join(testDir, "amp-hook-output.txt");
    const command = `echo SAFE\\; echo $AMP_HOOK_VALUE > ${JSON.stringify(outputPath)}`;
    const ampHooks = AmpHooks.fromRulesyncHooks({
      outputRoot: testDir,
      rulesyncHooks: buildRulesyncHooks({
        testDir,
        config: { hooks: { sessionStart: [{ command }] } },
      }),
      validate: false,
    });
    const pluginsDir = join(testDir, ".amp", "plugins");
    await ensureDir(pluginsDir);
    const pluginPath = join(pluginsDir, "rulesync-hooks.ts");
    await writeFileContent(pluginPath, ampHooks.getFileContent());
    const runnerPath = join(testDir, "run-amp-hook.ts");
    await writeFileContent(
      runnerPath,
      [
        'import { $ } from "bun";',
        `import plugin from ${JSON.stringify(pluginPath)};`,
        "let sessionStart;",
        'plugin({ on: (event, handler) => { if (event === "session.start") sessionStart = handler; } });',
        'await sessionStart({ thread: { id: "T-test" } }, { $ });',
      ].join("\n"),
    );

    await execFileAsync("bun", [runnerPath], {
      env: { ...process.env, AMP_HOOK_VALUE: "expanded" },
    });
    expect(await readFileContent(outputPath)).toBe("SAFE; echo expanded\n");
  });

  it("should load and create a deletion instance for the generated plugin", async () => {
    const pluginsDir = join(testDir, ".amp", "plugins");
    await ensureDir(pluginsDir);
    await writeFileContent(join(pluginsDir, "rulesync-hooks.ts"), "export default function () {}");

    const loaded = await AmpHooks.fromFile({ outputRoot: testDir, validate: false });
    expect(loaded.getFileContent()).toBe("export default function () {}");

    const deletion = AmpHooks.forDeletion({
      outputRoot: testDir,
      relativeDirPath: join(".amp", "plugins"),
      relativeFilePath: "rulesync-hooks.ts",
    });
    expect(deletion.getFileContent()).toBe("");
    expect(deletion.isDeletable()).toBe(true);
  });

  it("should reject import because generated plugins cannot be parsed", () => {
    const ampHooks = new AmpHooks({
      outputRoot: testDir,
      relativeDirPath: join(".amp", "plugins"),
      relativeFilePath: "rulesync-hooks.ts",
      fileContent: "export default function () {}",
      validate: false,
    });
    expect(() => ampHooks.toRulesyncHooks()).toThrow(
      "Not implemented because generated Amp TypeScript plugins cannot be imported.",
    );
  });
});
