import { CONTROL_CHARS, type HooksConfig } from "../../types/hooks.js";

const AMP_TOOL_EVENTS = new Set(["tool.call", "tool.result"]);

type Handler = { command: string; matcher?: string };
type HandlerGroup = Record<string, Handler[]>;

function matcherToEmbeddedLiteral(matcher: string): string {
  let sanitized = matcher;
  for (const char of CONTROL_CHARS) {
    sanitized = sanitized.replaceAll(char, "");
  }
  if (sanitized === "*") {
    sanitized = ".*";
  }
  try {
    new RegExp(sanitized);
  } catch {
    throw new Error(`Invalid regex pattern in hook matcher: ${sanitized}`);
  }
  return JSON.stringify(sanitized);
}

function collectHandlers({
  effectiveHooks,
  eventMap,
}: {
  effectiveHooks: HooksConfig["hooks"];
  eventMap: Record<string, string>;
}): HandlerGroup {
  const handlerGroups: HandlerGroup = {};
  for (const [canonicalEvent, definitions] of Object.entries(effectiveHooks)) {
    const ampEvent = eventMap[canonicalEvent];
    if (!ampEvent) continue;

    const handlers = definitions
      .filter(
        (definition) =>
          (definition.type ?? "command") === "command" &&
          definition.command &&
          (!definition.matcher || AMP_TOOL_EVENTS.has(ampEvent)),
      )
      .map((definition) => ({
        command: definition.command as string,
        matcher: definition.matcher || undefined,
      }));
    if (handlers.length === 0) continue;

    const existing = handlerGroups[ampEvent];
    if (existing) {
      existing.push(...handlers);
    } else {
      handlerGroups[ampEvent] = handlers;
    }
  }
  return handlerGroups;
}

function buildCommandLines({
  handler,
  usesToolName,
  blocksToolCall,
}: {
  handler: Handler;
  usesToolName: boolean;
  blocksToolCall: boolean;
}): string[] {
  const lines: string[] = [];
  const indent = usesToolName && handler.matcher ? "      " : "    ";
  if (usesToolName && handler.matcher) {
    lines.push(
      `    if (new RegExp(${matcherToEmbeddedLiteral(handler.matcher)}).test(event.tool)) {`,
    );
  }

  if (blocksToolCall) {
    lines.push(`${indent}try {`);
    lines.push(
      `${indent}  const result = await ctx.$\`\${{ raw: ${JSON.stringify(handler.command)} }}\`;`,
    );
    lines.push(`${indent}  if (result.exitCode !== 0) {`);
    lines.push(
      `${indent}    const message = String(result.stderr).trim() || String(result.stdout).trim() || \`Hook command failed with exit code \${result.exitCode}.\`;`,
    );
    lines.push(`${indent}    return { action: "reject-and-continue", message };`);
    lines.push(`${indent}  }`);
    lines.push(`${indent}} catch (error) {`);
    lines.push(
      `${indent}  const message = error instanceof Error ? error.message : String(error);`,
    );
    lines.push(`${indent}  return { action: "reject-and-continue", message };`);
    lines.push(`${indent}}`);
  } else {
    lines.push(`${indent}await ctx.$\`\${{ raw: ${JSON.stringify(handler.command)} }}\`;`);
  }

  if (usesToolName && handler.matcher) {
    lines.push("    }");
  }
  return lines;
}

function buildSubscriptionLines(handlerGroups: HandlerGroup): string[] {
  const lines: string[] = [];
  for (const [ampEvent, handlers] of Object.entries(handlerGroups)) {
    const usesToolName =
      AMP_TOOL_EVENTS.has(ampEvent) && handlers.some((handler) => handler.matcher);
    const blocksToolCall = ampEvent === "tool.call";
    lines.push(
      `  amp.on(${JSON.stringify(ampEvent)}, async (${usesToolName ? "event, ctx" : "_event, ctx"}) => {`,
    );
    for (const handler of handlers) {
      lines.push(...buildCommandLines({ handler, usesToolName, blocksToolCall }));
    }
    if (blocksToolCall) {
      lines.push('    return { action: "allow" };');
    } else if (ampEvent === "agent.start") {
      lines.push("    return {};");
    }
    lines.push("  });");
  }
  return lines;
}

/** Generate the rulesync-owned Amp TypeScript plugin for canonical command hooks. */
export function generateAmpPluginCode({
  config,
  supportedEvents,
  eventMap,
}: {
  config: HooksConfig;
  supportedEvents: readonly string[];
  eventMap: Record<string, string>;
}): string {
  const supported = new Set(supportedEvents);
  const configHooks = { ...config.hooks, ...config.amp?.hooks };
  const effectiveHooks: HooksConfig["hooks"] = {};
  for (const [event, definitions] of Object.entries(configHooks)) {
    if (supported.has(event)) effectiveHooks[event] = definitions;
  }

  const subscriptionLines = buildSubscriptionLines(collectHandlers({ effectiveHooks, eventMap }));
  const lines = ["// Generated by rulesync. Do not edit manually."];
  if (subscriptionLines.length === 0) {
    lines.push("export default function () {}", "");
    return lines.join("\n");
  }

  lines.push('import type { PluginAPI } from "@ampcode/plugin";', "");
  lines.push("export default function (amp: PluginAPI) {");
  lines.push(...subscriptionLines);
  lines.push("}", "");
  return lines.join("\n");
}
