import { CONTROL_CHARS, type HooksConfig } from "../../types/hooks.js";

/**
 * Marker line every generated hook script carries. Cline resolves hooks by
 * exact event name from a directory users also hand-author scripts in, so the
 * marker is what tells a rulesync-owned script apart from a user's own: only
 * files carrying it are rewritten or cleaned up.
 */
export const CLINE_HOOK_SCRIPT_MARKER = "rulesync-owned: cline-hooks";

/** Exit code a hook command uses to cancel the task (Claude Code convention). */
const CANCEL_EXIT_CODE = 2;

function sanitizeCommand(command: string): string {
  let sanitized = command;
  for (const char of CONTROL_CHARS) {
    sanitized = sanitized.replaceAll(char, "");
  }
  return sanitized;
}

/** Single-quote a string for POSIX shells. */
function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

/** Single-quote a string for PowerShell. */
function powerShellQuote(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

export function collectClineHookCommands({
  effectiveHooks,
  eventMap,
}: {
  effectiveHooks: HooksConfig["hooks"];
  eventMap: Record<string, string>;
}): Record<string, string[]> {
  const commandsByEvent: Record<string, string[]> = {};
  for (const [canonicalEvent, definitions] of Object.entries(effectiveHooks)) {
    const clineEvent = eventMap[canonicalEvent];
    if (!clineEvent) continue;

    const commands = definitions
      .filter((definition) => (definition.type ?? "command") === "command" && definition.command)
      .map((definition) => sanitizeCommand(definition.command as string))
      .filter((command) => command.trim() !== "");
    if (commands.length === 0) continue;

    const existing = commandsByEvent[clineEvent];
    if (existing) {
      existing.push(...commands);
    } else {
      commandsByEvent[clineEvent] = commands;
    }
  }
  return commandsByEvent;
}

/**
 * A POSIX wrapper script for one Cline hook event.
 *
 * Cline spawns the file itself (`spawn(scriptPath, [], { shell: true })`), feeds
 * the event payload on stdin and reads a JSON result from stdout. The wrapper
 * therefore forwards the payload to each configured command in order and
 * translates the exit codes: `2` cancels the task, any other failure is
 * reported through `errorMessage` without cancelling, mirroring how the
 * canonical `command` hook type behaves for the tools that support blocking.
 */
export function generateClineHookScript({
  event,
  commands,
}: {
  event: string;
  commands: string[];
}): string {
  const lines = [
    "#!/bin/bash",
    `# ${event} hook generated by rulesync — edit .rulesync/hooks.jsonc and regenerate.`,
    `# ${CLINE_HOOK_SCRIPT_MARKER}`,
    "",
    "payload=$(cat)",
    "cancel=false",
    "error_message=''",
    "",
  ];

  for (const command of commands) {
    const quoted = shellQuote(command);
    lines.push(
      'if [ "$cancel" = false ]; then',
      // The command is passed as a single quoted argument rather than spliced
      // into this script, so its own quotes, comments and operators cannot
      // break the wrapper. A command the shell cannot parse would exit 2 —
      // the cancel code — so its syntax is checked first and a typo reports an
      // error instead of silently cancelling the task.
      `  if bash -n -c ${quoted} 2>/dev/null; then`,
      `    hook_stderr=$(printf '%s' "$payload" | bash -c ${quoted} 2>&1 >/dev/null)`,
      "    hook_status=$?",
      `    if [ "$hook_status" -eq ${CANCEL_EXIT_CODE} ]; then`,
      "      cancel=true",
      '      error_message="$hook_stderr"',
      '    elif [ "$hook_status" -ne 0 ]; then',
      `      printf '%s\\n' "rulesync ${event} hook failed (exit $hook_status): $hook_stderr" >&2`,
      '      error_message="$hook_stderr"',
      "    fi",
      "  else",
      `    error_message="rulesync ${event} hook command is not valid shell syntax"`,
      `    printf '%s\\n' "$error_message" >&2`,
      "  fi",
      "fi",
      "",
    );
  }

  lines.push(
    "escape_json() {",
    // Newlines, tabs and carriage returns become spaces and any other control
    // character is dropped: a raw control character in a JSON string makes the
    // whole result unparseable, which would silently discard a `cancel`.
    `  printf '%s' "$1" | tr '\\n\\r\\t' '   ' | tr -d '\\000-\\037' | sed -e 's/\\\\/\\\\\\\\/g' -e 's/"/\\\\"/g'`,
    "}",
    "",
    `printf '{"cancel": %s, "contextModification": "", "errorMessage": "%s"}\\n' "$cancel" "$(escape_json "$error_message")"`,
    "",
  );

  return lines.join("\n");
}

/**
 * The PowerShell twin of {@link generateClineHookScript}. On Windows Cline
 * resolves only `<Event>.ps1` and runs it through `powershell -File`, so both
 * spellings are written and the platform picks one.
 */
export function generateClineHookPowerShellScript({
  event,
  commands,
}: {
  event: string;
  commands: string[];
}): string {
  const lines = [
    `# ${event} hook generated by rulesync — edit .rulesync/hooks.jsonc and regenerate.`,
    `# ${CLINE_HOOK_SCRIPT_MARKER}`,
    "",
    "$payload = [Console]::In.ReadToEnd()",
    "$cancel = $false",
    "$errorMessage = ''",
    "",
  ];

  for (const command of commands) {
    lines.push(
      "if (-not $cancel) {",
      `  $hookStderr = ($payload | & cmd /c ${powerShellQuote(command)} 2>&1 | Out-String)`,
      "  $hookStatus = $LASTEXITCODE",
      `  if ($hookStatus -eq ${CANCEL_EXIT_CODE}) {`,
      "    $cancel = $true",
      "    $errorMessage = $hookStderr",
      "  } elseif ($hookStatus -ne 0) {",
      `    Write-Error ${powerShellQuote(`rulesync ${event} hook failed`)}`,
      "    $errorMessage = $hookStderr",
      "  }",
      "}",
      "",
    );
  }

  lines.push(
    "@{",
    "  cancel = $cancel",
    '  contextModification = ""',
    "  errorMessage = $errorMessage",
    "} | ConvertTo-Json -Compress",
    "",
  );

  return lines.join("\n");
}
