import { join } from "node:path";

import {
  PI_AGENT_EXTENSIONS_DIR_PATH,
  PI_EXTENSIONS_DIR_PATH,
  PI_HOOKS_FILE_NAME,
} from "../../constants/pi-paths.js";
import type { AiFileParams, ValidationResult } from "../../types/ai-file.js";
import {
  CANONICAL_TO_PI_EVENT_NAMES,
  PI_HOOK_EVENTS,
  type HookDefinition,
  type HooksConfig,
} from "../../types/hooks.js";
import { readFileContent } from "../../utils/file.js";
import type { RulesyncHooks } from "./rulesync-hooks.js";
import {
  ToolHooks,
  type ToolHooksForDeletionParams,
  type ToolHooksFromFileParams,
  type ToolHooksFromRulesyncHooksParams,
  type ToolHooksSettablePaths,
} from "./tool-hooks.js";

const OWNERSHIP_MARKER = "// Generated by RuleSync. Do not edit.";

type ExportedHook = Pick<HookDefinition, "command" | "matcher" | "timeout">;

function effectiveHooks(config: HooksConfig): Record<string, HookDefinition[]> {
  const shared = config.hooks as Record<string, HookDefinition[]>;
  const overrides = config.pi?.hooks as Record<string, HookDefinition[]> | undefined;
  return { ...shared, ...overrides };
}

function collectHandlers(config: HooksConfig): Record<string, ExportedHook[]> {
  const result: Record<string, ExportedHook[]> = {};
  const hooks = effectiveHooks(config);
  for (const canonicalEvent of PI_HOOK_EVENTS) {
    const definitions = hooks[canonicalEvent] ?? [];
    const exported = definitions
      .filter((definition) => (definition.type ?? "command") === "command" && definition.command)
      .map(({ command, matcher, timeout }) => ({ command, matcher, timeout }));
    if (exported.length > 0) result[canonicalEvent] = exported;
  }
  return result;
}

export function generatePiExtensionCode(config: HooksConfig): string {
  const handlers = collectHandlers(config);
  const serializedHandlers = JSON.stringify(handlers);
  const serializedEventMap = JSON.stringify(CANONICAL_TO_PI_EVENT_NAMES);
  return `${OWNERSHIP_MARKER}
import { spawn } from "node:child_process";
import type { ExtensionAPI, ExtensionContext } from "@earendil-works/pi-coding-agent";

type Hook = { command: string; matcher?: string; timeout?: number };
const hooks = ${serializedHandlers} as Record<string, Hook[]>;
const eventMap = ${serializedEventMap} as Record<string, string>;

function matches(matcher: string | undefined, value: string): boolean {
  if (!matcher || matcher === "*") return true;
  try {
    return new RegExp(matcher).test(value);
  } catch {
    return false;
  }
}

async function runHook(
  hook: Hook,
  canonicalEvent: string,
  piEvent: string,
  event: unknown,
  ctx: ExtensionContext,
): Promise<void> {
  const payload = {
    hook_event_name: canonicalEvent,
    pi_event_name: piEvent,
    cwd: ctx.cwd,
    event,
  };
  await new Promise<void>((resolve) => {
    const child = spawn(hook.command, {
      cwd: ctx.cwd,
      shell: true,
      stdio: ["pipe", "ignore", "ignore"],
      timeout: hook.timeout === undefined ? undefined : hook.timeout * 1000,
    });
    child.on("error", () => resolve());
    child.on("close", () => resolve());
    child.stdin?.end(JSON.stringify(payload));
  });
}

async function run(
  canonicalEvent: string,
  piEvent: string,
  event: unknown,
  ctx: ExtensionContext,
  toolName?: string,
): Promise<void> {
  for (const hook of hooks[canonicalEvent] ?? []) {
    if (toolName !== undefined && !matches(hook.matcher, toolName)) continue;
    await runHook(hook, canonicalEvent, piEvent, event, ctx);
  }
}

export default function rulesyncHooks(pi: ExtensionAPI): void {
  pi.on("session_start", async (event, ctx) => {
    await run("sessionStart", "session_start", event, ctx);
  });
  pi.on("session_shutdown", async (event, ctx) => {
    await run("sessionEnd", "session_shutdown", event, ctx);
  });
  pi.on("input", async (event, ctx) => {
    await run("beforeSubmitPrompt", "input", event, ctx);
  });
  pi.on("context", async (event, ctx) => {
    await run("preModelInvocation", "context", event, ctx);
  });
  pi.on("turn_end", async (event, ctx) => {
    await run("postModelInvocation", "turn_end", event, ctx);
  });
  pi.on("tool_call", async (event, ctx) => {
    for (const hook of hooks.preToolUse ?? []) {
      if (!matches(hook.matcher, event.toolName)) continue;
      await runHook(hook, "preToolUse", "tool_call", event, ctx);
    }
  });
  pi.on("tool_result", async (event, ctx) => {
    if (!event.isError) {
      for (const hook of hooks.postToolUse ?? []) {
        if (matches(hook.matcher, event.toolName))
          await runHook(hook, "postToolUse", "tool_result", event, ctx);
      }
    }
    if (event.isError) {
      for (const hook of hooks.postToolUseFailure ?? []) {
        if (matches(hook.matcher, event.toolName))
          await runHook(hook, "postToolUseFailure", "tool_result", event, ctx);
      }
    }
  });
  pi.on("agent_end", async (event, ctx) => {
    await run("stop", "agent_end", event, ctx);
  });
  pi.on("session_before_compact", async (event, ctx) => {
    await run("preCompact", "session_before_compact", event, ctx);
  });
  pi.on("session_before_tree", async (event, ctx) => {
    await run("contextOffload", "session_before_tree", event, ctx);
  });
}
`;
}

export class PiHooks extends ToolHooks {
  constructor(params: AiFileParams) {
    super({ ...params, fileContent: params.fileContent ?? "" });
  }

  static getSettablePaths(options?: { global?: boolean }): ToolHooksSettablePaths {
    return {
      relativeDirPath: options?.global ? PI_AGENT_EXTENSIONS_DIR_PATH : PI_EXTENSIONS_DIR_PATH,
      relativeFilePath: PI_HOOKS_FILE_NAME,
    };
  }

  static async fromFile({
    outputRoot = process.cwd(),
    validate = true,
    global = false,
  }: ToolHooksFromFileParams): Promise<PiHooks> {
    const paths = PiHooks.getSettablePaths({ global });
    const fileContent = await readFileContent(
      join(outputRoot, paths.relativeDirPath, paths.relativeFilePath),
    );
    return new PiHooks({ outputRoot, ...paths, fileContent, validate });
  }

  static fromRulesyncHooks({
    outputRoot = process.cwd(),
    rulesyncHooks,
    validate = true,
    global = false,
  }: ToolHooksFromRulesyncHooksParams & { global?: boolean }): PiHooks {
    const paths = PiHooks.getSettablePaths({ global });
    return new PiHooks({
      outputRoot,
      ...paths,
      fileContent: generatePiExtensionCode(rulesyncHooks.getJson()),
      validate,
    });
  }

  static forDeletion({
    outputRoot = process.cwd(),
    relativeDirPath,
    relativeFilePath,
  }: ToolHooksForDeletionParams): PiHooks {
    return new PiHooks({
      outputRoot,
      relativeDirPath,
      relativeFilePath,
      fileContent: "",
      validate: false,
    });
  }

  static isDeletable(instance: ToolHooks): boolean {
    return instance.getFileContent().startsWith(OWNERSHIP_MARKER);
  }

  toRulesyncHooks(): RulesyncHooks {
    throw new Error("Pi hooks do not support importing generated extensions.");
  }

  validate(): ValidationResult {
    return { success: true, error: null };
  }
}
