name: Select OpenCode model
description: Selects OpenRouter model based on comment text
inputs:
  comment-body:
    description: Comment body to inspect for model keywords
    required: true
outputs:
  model:
    description: Selected OpenRouter model
    value: ${{ steps.select-model.outputs.model }}
  comment-body-cleaned:
    description: Comment body with model keywords removed
    value: ${{ steps.select-model.outputs.comment_body_cleaned }}
runs:
  using: composite
  steps:
    - name: Determine model based on comment
      id: select-model
      shell: bash
      env:
        COMMENT_BODY: ${{ inputs.comment-body }}
      run: |
        if [[ "$COMMENT_BODY" == *"codex"* ]]; then
          echo "model=openrouter/openai/gpt-5.2-codex" >> $GITHUB_OUTPUT
        elif [[ "$COMMENT_BODY" == *"glm"* ]]; then
          echo "model=openrouter/z-ai/glm-5" >> $GITHUB_OUTPUT
        elif [[ "$COMMENT_BODY" == *"kimi"* ]]; then
          echo "model=openrouter/moonshotai/kimi-k2.5" >> $GITHUB_OUTPUT
        else
          echo "model=zai-coding-plan/glm-5" >> $GITHUB_OUTPUT
        fi
        CLEANED_COMMENT_BODY="$COMMENT_BODY"
        CLEANED_COMMENT_BODY="${CLEANED_COMMENT_BODY//\/oc/}"
        CLEANED_COMMENT_BODY="${CLEANED_COMMENT_BODY//\/opencode/}"
        CLEANED_COMMENT_BODY="${CLEANED_COMMENT_BODY//codex/}"
        CLEANED_COMMENT_BODY="${CLEANED_COMMENT_BODY//glm/}"
        CLEANED_COMMENT_BODY="${CLEANED_COMMENT_BODY//kimi/}"
        echo "comment_body_cleaned=$CLEANED_COMMENT_BODY" >> $GITHUB_OUTPUT
