import { readFileSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

import { globbySync } from "globby";

import { renderHookEventsMatrix } from "./hook-events-table.js";
import { repoRoot, runOxfmt } from "./run-oxfmt.js";

/**
 * Embed the canonical `docs/**\/*.md` hierarchy into a generated TypeScript
 * module so the `rulesync docs` command can serve it from every distribution
 * (npm dist bundles and bun-compiled binaries alike). The generated file is
 * committed; CI fails on drift via `pnpm run check:docs-content`.
 */
const docsRoot = join(repoRoot, "docs");
const outputPath = join(repoRoot, "src", "generated", "docs-content.ts");

// Regenerate the derived hook-event matrix inside file-formats.md before
// embedding, so a stale committed table fails the docs-content drift check
// (`check:docs-content` diffs this file as well as the embed). Written
// unconditionally: the renderer emits cells without column padding and oxfmt
// owns the final column layout, mirroring generate-supported-tools-tables.ts.
const hookMatrixPath = join(docsRoot, "reference", "file-formats.md");
writeFileSync(hookMatrixPath, renderHookEventsMatrix(readFileSync(hookMatrixPath, "utf8")), "utf8");
runOxfmt([hookMatrixPath]);

const filePaths = globbySync("**/*.md", {
  cwd: docsRoot,
  // The VitePress internals and the landing page (theme-config frontmatter,
  // not documentation) are not documentation content.
  ignore: [".vitepress/**", "node_modules/**", "index.md"],
});

const entries = filePaths
  .map((filePath) => {
    const id = filePath.split(sep).join("/").replace(/\.md$/, "");
    // Normalize line endings so a CRLF checkout (Windows autocrlf) cannot
    // drift the generated file.
    const content = readFileSync(join(docsRoot, filePath), "utf8").replaceAll("\r\n", "\n");
    return { id, content };
  })
  .toSorted((a, b) => (a.id < b.id ? -1 : 1));

const lines: string[] = [
  "// Auto-generated by scripts/generate-docs-content.ts. Do not edit manually.",
  "// Regenerate with `pnpm run generate:docs-content`.",
  "",
  "/**",
  " * The bundled documentation tree, keyed by document identifier (the path",
  " * under `docs/` without the `.md` extension, e.g. `guide/configuration`).",
  " */",
  "export const DOCS_CONTENT: Record<string, string> = {",
  ...entries.map(({ id, content }) => `  ${JSON.stringify(id)}: ${JSON.stringify(content)},`),
  "};",
  "",
];

writeFileSync(outputPath, lines.join("\n"), "utf8");
runOxfmt([outputPath]);
// oxlint-disable-next-line no-console
console.log(`Embedded ${entries.length} docs into ${relative(repoRoot, outputPath)}`);
