import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

import { globbySync } from "globby";

/**
 * Embed the canonical `docs/**\/*.md` hierarchy into a generated TypeScript
 * module so the `rulesync docs` command can serve it from every distribution
 * (npm dist bundles and bun-compiled binaries alike). The generated file is
 * committed; CI fails on drift via `pnpm run check:docs-content`.
 */
const repoRoot = join(import.meta.dirname, "..");
const docsRoot = join(repoRoot, "docs");
const outputPath = join(repoRoot, "src", "generated", "docs-content.ts");

const filePaths = globbySync("**/*.md", {
  cwd: docsRoot,
  // The VitePress internals are not documentation content.
  ignore: [".vitepress/**", "node_modules/**"],
});

const entries = filePaths
  .map((filePath) => {
    const id = filePath.split(sep).join("/").replace(/\.md$/, "");
    const content = readFileSync(join(docsRoot, filePath), "utf8");
    return { id, content };
  })
  .toSorted((a, b) => (a.id < b.id ? -1 : 1));

const lines: string[] = [
  "// Auto-generated by scripts/generate-docs-content.ts. Do not edit manually.",
  "// Regenerate with `pnpm run generate:docs-content`.",
  "",
  "/**",
  " * The bundled documentation tree, keyed by document identifier (the path",
  " * under `docs/` without the `.md` extension, e.g. `guide/configuration`).",
  " */",
  "export const DOCS_CONTENT: Record<string, string> = {",
  ...entries.map(({ id, content }) => `  ${JSON.stringify(id)}: ${JSON.stringify(content)},`),
  "};",
  "",
];

writeFileSync(outputPath, lines.join("\n"), "utf8");
// Normalize to the repo's formatter so the drift check compares stable output.
execFileSync("npx", ["oxfmt", relative(repoRoot, outputPath)], { cwd: repoRoot, stdio: "ignore" });
// oxlint-disable-next-line no-console
console.log(`Embedded ${entries.length} docs into ${relative(repoRoot, outputPath)}`);
