// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using RuleSync.Sdk.Models;
using Xunit;

namespace RuleSync.Sdk.Tests;

public class ModelTests
{
    [Theory]
    [InlineData(Feature.Rules, "rules")]
    [InlineData(Feature.Ignore, "ignore")]
    [InlineData(Feature.Mcp, "mcp")]
    [InlineData(Feature.Subagents, "subagents")]
    [InlineData(Feature.Commands, "commands")]
    [InlineData(Feature.Skills, "skills")]
    [InlineData(Feature.Hooks, "hooks")]
    public void Feature_Enum_HasExpectedValues(Feature feature, string expectedName)
    {
        Assert.Equal(expectedName, feature.ToString().ToLowerInvariant());
    }

    [Theory]
    [InlineData(ToolTarget.Claudecode, "claudecode")]
    [InlineData(ToolTarget.Cursor, "cursor")]
    [InlineData(ToolTarget.Copilot, "copilot")]
    [InlineData(ToolTarget.Windsurf, "windsurf")]
    public void ToolTarget_Enum_HasExpectedValues(ToolTarget target, string expectedName)
    {
        Assert.Equal(expectedName, target.ToString().ToLowerInvariant());
    }

    [Fact]
    public void GenerateOptions_DefaultValues_AreCorrect()
    {
        var options = new GenerateOptions();

        Assert.Null(options.Targets);
        Assert.Null(options.Features);
        Assert.Null(options.BaseDirs);
        Assert.Null(options.ConfigPath);
        Assert.Equal(false, options.Verbose);
        Assert.Equal(true, options.Silent);
        Assert.Equal(false, options.Delete);
        Assert.Equal(false, options.Global);
        Assert.Equal(false, options.SimulateCommands);
        Assert.Equal(false, options.SimulateSubagents);
        Assert.Equal(false, options.SimulateSkills);
        Assert.Equal(false, options.DryRun);
        Assert.Equal(false, options.Check);
    }

    [Fact]
    public void GenerateOptions_CanSetProperties()
    {
        var options = new GenerateOptions
        {
            Targets = new[] { ToolTarget.Claudecode, ToolTarget.Cursor },
            Features = new[] { Feature.Rules, Feature.Mcp },
            Verbose = true,
            Silent = false
        };

        Assert.Equal(2, options.Targets.Count);
        Assert.Equal(2, options.Features.Count);
        Assert.Equal(ToolTarget.Claudecode, options.Targets[0]);
        Assert.Equal(Feature.Rules, options.Features[0]);
        Assert.True(options.Verbose);
        Assert.False(options.Silent);
    }

    [Fact]
    public void ImportOptions_RequiresTarget()
    {
        var options = new ImportOptions
        {
            Target = ToolTarget.Claudecode,
            Features = new[] { Feature.Rules }
        };

        Assert.Equal(ToolTarget.Claudecode, options.Target);
        Assert.Single(options.Features);
    }

    [Fact]
    public void ImportOptions_DefaultValues_AreCorrect()
    {
        var options = new ImportOptions { Target = ToolTarget.Claudecode };

        Assert.Null(options.Features);
        Assert.Null(options.ConfigPath);
        Assert.Equal(false, options.Verbose);
        Assert.Equal(true, options.Silent);
        Assert.Equal(false, options.Global);
    }

    [Fact]
    public void GenerateResult_InitializesCollections()
    {
        var result = new GenerateResult();

        Assert.NotNull(result.RulesPaths);
        Assert.NotNull(result.IgnorePaths);
        Assert.NotNull(result.McpPaths);
        Assert.NotNull(result.CommandsPaths);
        Assert.NotNull(result.SubagentsPaths);
        Assert.NotNull(result.SkillsPaths);
        Assert.NotNull(result.HooksPaths);
        Assert.Empty(result.RulesPaths);
    }

    [Fact]
    public void GenerateResult_Serialization_RoundTrips()
    {
        var original = new GenerateResult
        {
            RulesCount = 5,
            RulesPaths = new[] { "path1.md", "path2.md" },
            IgnoreCount = 2,
            IgnorePaths = new[] { ".gitignore" }
        };

        var json = JsonSerializer.Serialize(original);
        var deserialized = JsonSerializer.Deserialize<GenerateResult>(json);

        Assert.NotNull(deserialized);
        Assert.Equal(5, deserialized.RulesCount);
        Assert.Equal(2, deserialized.RulesPaths.Count);
        Assert.Equal("path1.md", deserialized.RulesPaths[0]);
        Assert.Single(deserialized.IgnorePaths);
    }

    [Fact]
    public void ImportResult_Serialization_RoundTrips()
    {
        var original = new ImportResult
        {
            RulesCount = 5,
            IgnoreCount = 2,
            McpCount = 3
        };

        var json = JsonSerializer.Serialize(original);
        var deserialized = JsonSerializer.Deserialize<ImportResult>(json);

        Assert.NotNull(deserialized);
        Assert.Equal(5, deserialized.RulesCount);
        Assert.Equal(2, deserialized.IgnoreCount);
        Assert.Equal(3, deserialized.McpCount);
    }

    [Fact]
    public void Feature_Serialization_UsesCamelCase()
    {
        var feature = Feature.Rules;
        var json = JsonSerializer.Serialize(feature);

        // Enum values serialize as numbers by default with System.Text.Json
        // unless JsonStringEnumConverter is used
        Assert.Equal("0", json);
    }
}
